set(headers ${headers}
	include/Application.h
	include/Config.h
	include/HookBuilder.h
	include/Input.h
	include/Logger.h
	include/Model.h
	include/PCH.h
	include/Plugin.h
	include/Renderer.h
	include/SKSEMenuFramework.h
	include/UI.h
	include/Textures.h
	include/cimgui.h
	include/File.h
	imgui/backends/imgui_impl_dx11.h
    imgui/backends/imgui_impl_win32.h
    imgui/imconfig.h
    imgui/imgui.h
    imgui/imgui_internal.h
    imgui/imstb_rectpack.h
    imgui/imstb_textedit.h
    imgui/imstb_truetype.h
)
